djangoreport/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import login_view, logout_view


urlpatterns = [
    path('admin/', admin.site.urls),
    path('sales/', include('sales.urls', namespace='sales')),
    path('reports/', include('reports.urls', namespace='reports')),
    path('my_profile/', include('profiles.urls', namespace='profiles')),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    
]

urlpatterns +=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reports/urls.py
from django.urls import path
from .views import (ReportListView, 
                    ReportDetailView, 
                    UploadTemplateView, 
                    render_pdf_view, 
                    created_report_view,
                    csv_upload_view)

app_name='reports'

urlpatterns=[
    path('save/',created_report_view, name="create-report"),
    path('upload/',csv_upload_view, name="upload"),
    path('<int:pk>/pdf/',render_pdf_view, name="report-generate"),
    path('',ReportListView.as_view(), name="report-list"),
    path('<int:pk>/',ReportDetailView.as_view(), name="report-detail"),
    path('from_file/',UploadTemplateView.as_view(), name="from-file"),
]

sales/urls.py
from django.urls import path
from .views import (home_view, 
            SaleListView,
            SaleDetailsView)
app_name="sales"

urlpatterns = [
    path('', home_view, name='sales-home'),
    path('list/', SaleListView.as_view(), name='sale-list'),
    path('list/<int:pk>/', SaleDetailsView.as_view(), name='sale-details'),
]

reports/models.py
from django.db import models
from django.shortcuts import reverse
from profiles.models import Profile
# Create your models here.
class Report(models.Model):
    name = models.CharField(max_length=120)
    image= models.ImageField(upload_to='reports', blank=True)
    remarks= models.TextField()
    auth= models.ForeignKey(Profile, on_delete=models.CASCADE)
    created =models.DateTimeField(auto_now_add=True)
    updated =models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("reports:report-detail", kwargs={'pk': self.pk})

    class Meta:
        ordering = ('created',)

reports/forms.py
from django import forms
from .models import Report

class ReportForm(forms.ModelForm):
    class Meta:
        model = Report
        fields=(
            'name', 
            'remarks'
        )

reports/views.py
import csv
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, get_object_or_404
from django.http import JsonResponse, HttpResponse
from django.views.generic import ListView, DetailView, TemplateView
from django.template.loader import get_template
from django.utils.dateparse import parse_date
from .utils import get_report_image, link_callback
from .models import Report
from profiles.models import Profile
from products.models import Product
from customers.models import Customer
from sales.models import Sale, Position, CSV
from .forms import ReportForm
from xhtml2pdf import pisa
from datetime import datetime


# Create your views here.


class ReportListView(LoginRequiredMixin,ListView):
    model=Report
    template_name="reports/report_list.html"
    context_object_name="report_list"

class ReportDetailView(LoginRequiredMixin,DetailView):
    model=Report
    template_name="reports/report_detail.html"
    context_object_name="report"
    
class UploadTemplateView(LoginRequiredMixin,TemplateView):
    template_name="reports/from_file.html"

@login_required
def created_report_view(request):
    if request.is_ajax:
        name=request.POST.get('name')
        remarks=request.POST.get('remarks')
        image=request.POST.get('image')
        img =get_report_image(image)
        author=Profile.objects.get(user=request.user)
        Report.objects.create(name=name, image=img, remarks=remarks, auth=author)
        
        # form=ReportForm(request.POST or None)
        # if form.is_valid:
        #     instance=form.save(commit=False)
        #     image=request.POST.get('image')
        #     img =get_report_image(image)
        #     instance.image=img
        #     instance.auth=Profile.objects.get(user=request.user)
        #     instance.save()
        return JsonResponse({"message":"send"})
    return JsonResponse({"message":"not ajax call"})


# def render_pdf_view(request,pk):
#     template_path = 'reports/pdf.html'
#     report=get_object_or_404(Report, pk=pk)
#     context ={
#         "report": report
#     }
#     # context = {'myvar': 'this is your template context'}
#     # Create a Django response object, and specify content_type as pdf
#     response = HttpResponse(content_type='application/pdf')
#     #if download
#     # response['Content-Disposition'] = 'attachment; filename="report.pdf"'
#     #if display
#     response['Content-Disposition'] = f'inline; filename="report_{datetime.now()}.pdf"'
    
#     # find the template and render it.
#     template = get_template(template_path)
#     html = template.render(context)

#     # create a pdf
#     pisa_status = pisa.CreatePDF(
#        html, dest=response, link_callback=link_callback)
#     # if error then show some funy view
#     if pisa_status.err:
#        return HttpResponse('We had some errors <pre>' + html + '</pre>')
#     return response
@login_required
def render_pdf_view(request, pk):
    template_path = 'reports/pdf.html'
    report = get_object_or_404(Report, pk=pk)
    context = {'report': report}

    response = HttpResponse(content_type='application/pdf')

    response['Content-Disposition'] = 'filename="report.pdf"'

    template = get_template(template_path)
    html = template.render(context)

    pisa_status = pisa.CreatePDF(
       html, dest=response)

    if pisa_status.err:
       return HttpResponse('We had some errors <pre>' + html + '</pre>')
    return response

@login_required
def csv_upload_view(request):
    template_name="reports/file_upload.html"
    csv_file_name=request.FILES.get('file').name
    csv_file=request.FILES.get('file')
    obj, created =CSV.objects.get_or_create(file_name=csv_file_name)
    if created:
        obj.csv_file=csv_file
        obj.save()
        with open(obj.csv_file.path, 'r') as f:
            csv_read=csv.reader(f)
            csv_read.__next__()
            for row in csv_read:
                data="".join(row)
                data=data.split(';')
                data.pop()
                
                transaction_id=data[1]
                product=data[2]
                quantity=int(data[3])
                customer =data[4]
                date= datetime.combine(parse_date(data[5]), datetime.min.time())
                print(date)
                try:
                    product_obj=Product.objects.get(name__iexact=product)
                except Product.DoesNotExist:
                    product_obj = None
                print(product_obj)
                if product_obj is not None:
                    customer_obj, _ = Customer.objects.get_or_create(name=customer) 
                    salesman_obj = Profile.objects.get(user=request.user)
                    position_obj = Position.objects.create(product=product_obj, quantity=quantity, created=date)
                    sale_obj, _ = Sale.objects.get_or_create(transaction_id=transaction_id, customer=customer_obj, salesman=salesman_obj, created=date)
                    sale_obj.positions.add(position_obj)
                    sale_obj.save()
            return JsonResponse({"ex": False})   
    else:              
        return JsonResponse({"ex": True})   

reports/templates/reports/from_file.html
{% extends 'base.html'%}
{% load static %}

{%block scripts %}
    <script src="{% static 'reports/Upload.js' %}" defer></script>
{%endblock scripts %}

{%block title%}
    Upload sales files
{%endblock title%}

{%block content%}
    <h5>Upload your sales documents</h5>
    <div id=alert-box></div>
    <br>
    <form id="fileupload-dropzone" class="dropzone dzone">
        {% csrf_token %}
        <div class="fallback">
            <input name="file" type="file" multiple />
        </div>
    </form>
{%endblock content%}

reports/templates/reports/pdf.html
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">

  <title>PDF {{report.name}}</title>
  <style>
    .image {
        width: 100%;
        height: auto;
    }
  </style>
</head>
<body>
    <h1>{{report.name}}</h1>
    <hr>
    <img src={{report.image.path}} class="image">
    <br>
    <h3>Remarks</h3>
    <p>{{report.remarks}}</p>
    <hr>
    <p>author: <b>{{report.author.user.username}}</b></p>
    <p>created: <b>{{report.created}}</b></p>
    <p>{{report.image.path}}</p>
</body>
</html>

reports/templates/reports/report_detail.html
{% extends 'base.html' %}
{% load static %}

{%block title%}
Report Details
{% endblock %}

{%block content %}
    {% comment %} <div>
        <div class"w-full">
            <span class="">Report Name<span> {{report.name}}
        </div>
        <div>
            <h2>Remarks:</h2>{{report.remarks}}
        </div>
        <div><img src={{report.image.url}} class="img-fluid" /></div>
    </div>
    <a href="{% url 'reports:report-list' %}" class="btn btn-primary">view report list</a> {% endcomment %}
{% if report.image %}
    <div><img src={{report.image.url}} class="img-fluid" /></div>
{% endif %}
    <h3>Remarks:</h3>
    <p>{{report.remarks}}</p>
    <hr>
    <p>author: <b>{{report.auth.user.username}}</b></p>
    <p>created: <b>{{report.created}}</b></p>
     <a href="{% url 'reports:report-list' %}" class="btn btn-primary">view report list</a>
{% endblock %}

reports/templates/reports/report_list.html
{% extends 'base.html' %}
{% load static %}

{%block title%}
Report List
{% endblock %}

{%block content %}
    <p>Report List View</p>
   
    {% comment %} <div class="container">
        <div class="row"> {% endcomment %}
            {% for report in report_list %}
            {% comment %} <div class="col-sm-4"> {% endcomment %}
                <div class="card mb-3">
                    <img class="card-img-top img-fluid" src={{report.image.url}} alt="Card image cap">
                    <div class="card-body">
                    <h5 class="card-title">{{report.name}}</h5>
                    <p class="card-text">{{report.remarks |truncatewords:2}}</p>
                    <a href="{{ report.get_absolute_url }}" class="btn btn-primary">view report detail</a>
                    <a href="{% url 'reports:report-generate' report.pk %}" class="btn btn-danger">generate report</a>
                    </div>
                </div>
            {% comment %} </div> {% endcomment %}
            {% endfor %}
        {% comment %} </div>
    </div> {% endcomment %}
    
{% endblock %}